### ISSUE TITLE
no traffic generated at all and non error

### ISSUE THREAD

**Issue by Fabelab** [anthonyraymond/joal#102]
hello, I set up the cli tool (linux) and try the appimage (linux and windows) and both end up with 0 traffic:
![Screenshot from 2020-08-16 07-00-05](https://user-images.githubusercontent.com/7839545/90326886-3d004780-df8e-11ea-976d-1824c53e2aa9.png)
 There us surely something i do wrong, boy here are no warning or  error in output to help

thx in advance

**Comment by anthonyraymond** [comment]
Hello,

This is the expexted behavior because your torrent have 0 leechers (check the blue numbers on the leftside of the torrent)

You need to have at least 1 seeders and 1 leechers to generate upload. That's for security.

Try with more active torrents

Le 16 août 2020 à 09:34, à 09:34, Fa13e <notifications@github.com> a écrit:

**Comment by Fa13e** [comment]
I did try with others more active torrents but same results

**Comment by anthonyraymond** [comment]
Can you send a screenshot with your new torrents?
