### ISSUE TITLE
Serving files if available

### ISSUE THREAD

**Issue by varaxasthur** [anthonyraymond/joal#117]
Hey !

Very nice projet. thanks.
I don't know how much of the torrent protocol is actually embedded in this, but would there be a way to actually serve the files in case someone tries to leech off of you if you have said files ? That might throw off anti-cheat detection.

Another question, I might not have read properly but is the size reported variable ? (I assume that's why there are min and max rates in the configuration ?) I'm asking because the rate I see besides the torrent in the web UI is static.

Thanks for your time

**Comment by anthonyraymond** [comment]
Hello,

Thanks for you kind word, i appreciate your support :)

This next version (currently in development) will "choke" every clients asking for data (that's a part of the BT protocol), it happens when your client has already reached the maximum of leechers it can be connected to, every further clients attempting to connect are "chocked".
The current version is doing something quite like that but not exactly.

And for the speed, the min and max correspond to the data to generate per second (spread among all torrents). The speed seems static but it's actually re-evaluated every 15 or 20 minutes and it procudes a real randomized data flow.

the more you generate random numbers, the faster it converges to the median values. The refresh rate has been thinked a lot and this is the nicest spot to be on. You'll have to trust me on that (unless you want to dig on the source code and evaluates how it's refreshing on your own 😄)

**Comment by varaxasthur** [comment]
Very nice, thanks for the quick support too.
I've had my answers. Feel free to close this when you feel the issue has been addressed,
