### ISSUE TITLE
Torrents are getting archived unexpectedly

### ISSUE THREAD

**Issue by armandkd** [anthonyraymond/joal#123]
Hello,

I have noticed an issue when running torrents unmonitored for prolonged periods of time : they usually end up getting archived.
I have verified that there are still seeders during the whole time, and have checked _Keep seeding torrents even with no peers_ just to be safe. I also have rebooted the process (and docker) many times.

I've conducted a few tests and JOAL seems to archive torrents when the announces fail for any reason (lack of internet connectivity, tracker downtime,...). This doesn't seem to be configurable in the settings.
This is particularly annoying when dealing with spotty private trackers (more probable in my case) or poor internet connectivity.

Would it be possible to add a setting to keep the torrents seeding even when the announces are failing? Or maybe a setting to configure the number of failed announces before a torrent is archived?

I think I've narrowed it down to line 69 in file _src\main\java\org\araymond\joal\core\ttorrent\client\announcer\response\BandwidthDispatcherNotifier.java_, although I'm really not proficient in Java and doesn't know how to fix the issue myself.

Thank you very much for your amazing work !

**Comment by anthonyraymond** [comment]
Hello,

I'm completly rewriting JOAL in another language ATM, so i'm no longer adding feature to the current version.

What you are describing was the "expected behavior" with the current version of JOAL.
But looking back i feel like this was a bad idea in the first place, In the furture version torrent won't get archived due to network issue.
But this version is still in development and you'll need to wait a bit to be able to try it out.

**Comment by armandkd** [comment]
Thank you for your answer. Would you accept a merge request if I wrote one for this version of JOAL?

I haven't noticed a branch for the rewrite. In what language are you rewriting it? Do you need any help? :)

**Comment by anthonyraymond** [comment]
ATM the new version is in an organisation repo (which i think will be moved in this repo ultimately).
See => https://github.com/owl-torrent/joal-cli

It's written in golang and the CORE functionality seems to work really nice but still not tested nor analyzed properly, so it's not "safe" to use ATM.
If you know Golang and how fix some of the TODO feel free to do so ^^.

About the current version i won't accept PR because of the mess i could create, it's not just about "not removing", you also need to stop adding upload stat on the torrent, and also you need to start announcing on fallback tracker if there is some in the torrent file (but depending on the client you don't select the trackers the same way...) this is a pain in the ass to refactor as is. It's just to much work to make it legit. I honestly won't have time to give you a feedback on the PR if you happened to write the code. Plus this is already implemented in the new version so...

i guess you'll have to be patient for the release :)
