### ISSUE TITLE
Distribute upload speed evenly

### ISSUE THREAD

**Issue by Acrilez** [anthonyraymond/joal#199]
I have this issue with the docker version of joal when I set the up speed limit to 3400 - 5200 for example, only one torrent gets in that upload speed range. The others upload at 50-30 kbps and I got some warnings by my trackers because of low quality seeds.
Is there any way the the upload speed in ALL active torrents is within the range and not lower?

**Comment by Dysta** [comment]
Hello, same issue here but I launch with cmd line
my config
```json
{
  "minUploadRate" : 4700,
  "maxUploadRate" : 5300,
  "simultaneousSeed" : 5,
  "client" : "rtorrent-0.9.6_0.13.6.client",
  "keepTorrentWithZeroLeechers" : false
}
```
The command line
```bash
java -Xmx1G -jar ./jack-of-all-trades.jar --joal-conf="." \
	--spring.main.web-environment=true \
	--server.port=19987 \
	--joal.ui.path.prefix="-" \
	--joal.ui.secret-token="-"
```
and the result with 3 torrents
![image](https://user-images.githubusercontent.com/25008828/224962875-e3831b34-12bf-4863-88ee-c3dee75eea9a.png)

even with overall speed saying i'm at 5Mb/s
![image](https://user-images.githubusercontent.com/25008828/224963001-ffe8f353-69dc-4fb1-8d85-930dcb9ce1ab.png)

And I use the latest version of Joal (2.1.33)

**Comment by anthonyraymond** [comment]
Hello,

There is a no "speed by torrent" settings because it would be too dangerous for most of the users.
The global upload rate is splitted among all torrent, the lower the ratio seed/leech the more speed it gets allocated.

Joal was designed to be as simple to use as possible: drag and drop torrent in JOAL and voila. Don't overthing the whole process, it's just gonna work.

I don't get what you mean by low quality seed. Does your tracker warn you if your upload speed is too low on a particular torrent? That makes no sense, what kind of tracker do that? The essense of P2P is to open multiple connexion (of unpredictable and variable speed) to multiple sources/destination simultaneously. It makes no sense to judge the quality of a seed by it's speed...

Having that said if you want to have a fixed speed for a particular torrent you can set _simultaneousSeed_ to _1_ but it's not an optimal solution because you won't be able to seed multiple torrents at once.
