### ISSUE TITLE
Is it Open Source ? Which license ?

### ISSUE THREAD

**Issue by dlecan** [anthonyraymond/joal#3]
Is this project open source ? What is the license for this useful project ?

If you need help to choose: https://choosealicense.com/

Thanks

**Comment by anthonyraymond** [comment]
Well my project is totally open source. But i use an apache 2.0 licenced library. I suppose it makes my project an apache 2.0 as well. Otherwise i would have been instrested by [this one](https://github.com/SFEley/candy/blob/master/LICENSE.markdown)
But i havent included the Licence ans list of changes.

So... short answer is: i personnaly don't care, but i use an apache 2.0 library, so i don't know what to say.

**Comment by dlecan** [comment]
Apache license is a good one and compatible with your dependencies.
If you don't declare it explicitly, author rights apply, so you project wouldn't be open source.

You can:
- either declare Apache License v2.0 in your README file
- or just add a `LICENSE` file (beware of spelling if you are french) at the root of the repository with the content of the license: https://choosealicense.com/licenses/apache-2.0/

**Comment by anthonyraymond** [comment]
Is it ok if i add a `LICENSE` file? Don't i need to explicitly name my apache 2.0 dependencies in it?

**Comment by dlecan** [comment]
> Is it ok if i add a LICENSE file

Yes

> Don't i need to explicitly name my apache 2.0 dependencies in it?

No

**Comment by anthonyraymond** [comment]
Ok, thanks for your advices. I never really take times to dig into licensing. But now it's done for this repository.
Thanks to you ;)

May i ask why did you wanted to know about license? Do you plan to fork or build something on top of it?

**Comment by dlecan** [comment]
> May i ask why did you wanted to know about license?

I'm using Joal, I'm a developer: I always check if I am a able to contribute to a project.
Now, it's possible with Joal :)

**Comment by anthonyraymond** [comment]
Sure you are :) you even are welcome but keep in mind that this version of joal will become lecagy soon.
An issue about v2 #4 is opened to keep track of incoming change and roadmap.

Better take a look at `dev-v2` branch if you want to contribute. (Should be cleaner in few weeks, because i'm migrating to spring currently).
