### ISSUE TITLE
Joal deployment on heroku

### ISSUE THREAD

**Issue by geart891** [anthonyraymond/joal#36]
I deployed this on a heroku server, everything is working smoothly until I open the app.
I has `Failed to connect to Joal, retry in 8 seconds`
Then I open the console and find this error message `WebSocket connection to 'wss://xxxxxxxxxxxxxxxxxxxxxxxx:xx/yyyyyyyyyyyyyyyyyyyyyyyyyyyyy' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR`
Please help.

**Comment by anthonyraymond** [comment]
Yep, that's an expected behaviour. Joal does not supports SSL. (https or wss) officially.

Actually it's funny that you'd still successfully reach the webui over https, but it's about heroku acting as a reverse proxy and downgrade https to http before forwarding it to the app. But it seems not to do so with wss for some reasons. [See this SO post.](https://stackoverflow.com/a/36140419/2275818)

But be carefull, joal is not meant to be deployed to heroku, it's kinda easy for tracker admin to find out which ip range heroku is owning, and therefore ban you from the tracker.

A proper install of joal would be behind a reverse proxy on a server which will be behind your own router.
