### ISSUE TITLE
Unable to Access WebUI (joal running in docker - The URL was not normalized)

### ISSUE THREAD

**Issue by maxou2600** [anthonyraymond/joal#49]
Hi,

I'm unable to access the WebUI of Joal (firefox returns me 403 when I try to access
`http://server_ip/joal/secret_path/ui` )

Joal is running in a container (with `--net=container:container_name` to dperson/openvpn-client, 
(that works, when i run `docker logs joal`, i can see the public IP which is the VPN one))

I put a nginx reverse proxy (docker, alpine aarch64 image) to have an access to the WebUI, above is my 
/etc/nginx/conf.d/joal.conf

```
server {
   listen 80;
   server_name 192.XXX.X.XXX;

location /joal {
        proxy_pass http://joal:90XX/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Proxy "";

            proxy_http_version 1.1;
            proxy_set_header Connection "upgrade";
            proxy_set_header Upgrade $http_upgrade;
            proxy_read_timeout 600s;

            access_log off;
                }
}
```

when I try to access the WebUI, I got errors (in red) when I launch `docker logs joal`

`[ERROR] 2018-12-03 08:26:52.635 [http-nio-90XX-exec-3] o.a.c.c.C.[.[.[.[dispatcherServletRegistration]: Servlet.service() for servlet [dispatcherServletRegistration] in context with path [] threw exception                                                                                                                                     
org.springframework.security.web.firewall.RequestRejectedException: The request was rejected because the URL was not normalized. `

Thank you for your help :)

EDIT_1 : Solved the Access of the WebUI by correcting joal.conf ... (stupid error from me...)
new working UI conf 

```
server {
   listen 80;
   server_name 192.XXX.X.XXX;

location /joal/ {
        proxy_pass  http://joal:90XX/secret_path/ui/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Proxy "";

            proxy_http_version 1.1;
            proxy_set_header Connection "upgrade";
            proxy_set_header Upgrade $http_upgrade;
            proxy_read_timeout 600s;

            access_log off;
                }
}
```

But now it shows "Failed to connect to Joal", I changed the value in "Change connection settings" to

Server address : `192.XXX.X.XXX`
Server port : `80` (so it's nginx listening port)
Path prefix : `secret_path`  (in my case only numers)
Secret Token : `token` (special charac, letters, numbers, i set up in docker run command)

Is this right ?

**Comment by anthonyraymond** [comment]
Hi :)

I use kind of the same setup, if you router supports local*loopback you can try the nginx conf i've provided some time ago (https://github.com/anthonyraymond/joal/issues/33#issuecomment-399572788), remove non-relevant parts about SSL.

However this requires local-loopback supports, if you are unsure that your router does supports it, you can try with the following conf:


```
server {
    listen 80;
    server_name 192.XXX.X.XXX;

    location /joal/ {
        proxy_pass  http://joal:90XX/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Proxy "";
        proxy_http_version 1.1;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_read_timeout 600s;

        access_log off;
    }
}
```

I used to have this kind of config before, I can't remember exactly how nor why, but there is some shenanigans going with the slashes `/` in both location and proxy_pass.
Try with these combination:
- `location /joal/` and `proxy_pass http://joal:90XX/`
- `location /joal/` and `proxy_pass http://joal:90XX`
- `location /joal` and `proxy_pass http://joal:90XX/`
- `location /joal` and `proxy_pass http://joal:90XX`

One of those works (can't remember which nor why), i've since switched to a subdomain routing, i feel more comfortable with this (but once agan it requires local-loopback supports).


**Do not include the path prefix in the nginx conf, the point behind the path prefix is to prevent people from internet to known that joal is running just by checking http://ip/joal**.
Any request sent to Joal without the path-prefix will result as an HTTP 503 as a defensive measure to prevent people knowing that Joal is running on the server.


Values that you entered in "Change connection settings looks good to me" (as long as there are the same that you used to run Joal.

Let me known if you still have issues

**Comment by maxou2600** [comment]
Thank you :)

The good configuration is  `location /joal/` with `proxy_pass http://joal:90XX/`

Same as before, I can access the WebUI without any problem but it fails to connect to the server "retry in eight seconds"

I had to re-put the values by clicking the red button, but it does not work :(

**Comment by anthonyraymond** [comment]
Does the xonsole shows some more details? Ctrl + shift + i in chrome

**Comment by maxou2600** [comment]
![screenshot_20181204_131029](https://user-images.githubusercontent.com/13450985/49441509-fcb36280-f7c6-11e8-852a-7bd71e8a37cb.png)

This is what i get, thanks

**Comment by anthonyraymond** [comment]
oh it makes sense ^^
Well done :)
