### ISSUE TITLE
password protect aside the token ? 

### ISSUE THREAD

**Issue by silkyclouds** [anthonyraymond/joal#85]
Hi,

Is there any way to password protect the whole access to the web ui ? 

It is nice to have the token, but still, anyone can connect to the server on the configured port, and see joal is running. 

any clue ?

**Comment by anthonyraymond** [comment]
Thats why i introduce the mandatory ui field "joal.ui.path.prefix"

If you reach "http://server/port/" without the path there is now way to know thats you have reached a joal instance. I made sure that the server does not returns any hints.

Since the path is supposed to advises to be unguessable (if you red the doc ^^) there is now way to know that joal is running
